### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by cabban** [frafra/spotify-share-library#3]
shame its not working the link is dead :(

**Comment by frafra** [comment]
Hi!
You are right, the demo link is down, but the software works :)
I will put it online again soon. Stay tuned :)

**Comment by frafra** [comment]
I am back from summer holidays :) It should be available again in few hours.

**Comment by frafra** [comment]
Fixed! Thank you :)

**Comment by cabban** [comment]
Still same bad gateway 😪 is it fix or not 😀cheers
@frafra 
torsdag 19 augusti 2021 skrev Francesco Frassinelli <
***@***.***>:

**Comment by cabban** [comment]
![image](https://user-images.githubusercontent.com/19514493/130352453-68b3c49b-a5e8-4664-94a5-5acd425127c6.png)

**Comment by frafra** [comment]
It went down again, you are right, sorry; I will fix it later today :)

**Comment by frafra** [comment]
Fixed :)

**Comment by cabban** [comment]
yes yes :) thank you :)=  @frafra
